### ISSUE TITLE
Rename the environment variable to DATABASE

### ISSUE THREAD

**Issue by kshitij10496** [kshitij10496/hercules#15]
The MVP of `hercules` used `DATABASE_URL` environment variable for the DB connection string.
Thanks to #6, we are now using `envconfig` for the management of configuration values.
Currently, the developer is required to set `HERCULES_DATABASEURL` for the same DB connection.

It would be aesthetically pleasing if someone can rename the variable to `HERCULES_DATABASE` instead.

**Comment by mels065** [comment]
I'll give it a go
