### ISSUE TITLE
Create a project landing page

### ISSUE THREAD

**Issue by kshitij10496** [kshitij10496/hercules#16]
Currently, landing on the [homepage](https://hercules-10496.herokuapp.com/) results in a 404. 
It would be cool if we could list all the endpoints currently supported by the API populated from [this](https://github.com/kshitij10496/hercules#implementation) section for the time being.

I would be happy with a skeleton page, mostly using HTML and CSS.

**Comment by rasfa98** [comment]
Can I work on this? And if so, in what folder should I add the 404.html page?

**Comment by rasfa98** [comment]
I placed the index.html file together with the css in a folder named "static" located in the root of the project.

**Comment by kshitij10496** [comment]
Thanks for taking this up @rasfa98 ❤️ 
A `static` folder, as you suggested, sounds good to me!

**Comment by kshitij10496** [comment]
Closed #19
