### ISSUE TITLE
Pretty JSON response from API endpoints

### ISSUE THREAD

**Issue by kshitij10496** [kshitij10496/hercules#26]
At the moment, the JSON response from the API is raw and hinders human readability.
It would be ideal if we could prettify the responses.

**Possible Fix**: The task would probably require edits in the JSON Encoder present in `RespondWithJSON`.

*References* 
[1]: https://stackoverflow.com/questions/19038598/how-can-i-pretty-print-json-using-go
[2]: https://godoc.org/encoding/json

**Comment by kamidipreetham** [comment]
Can I work on this ?

**Comment by kshitij10496** [comment]
Hey @kamidipreetham 👋 
Let me know if you are facing any issues with the fix. 😄

**Comment by jegutierrez** [comment]
Hey @kshitij10496, @kamidipreetham I send a PR, let me know what do you think about the solution 😄
