### ISSUE TITLE
Draw hercules art

### ISSUE THREAD

**Issue by kshitij10496** [kshitij10496/hercules#3]
Add a cool and funny doodle! 🎨 
It would be nice if the art could be associated/symbolise strength and power in an abstract way. 💪 

This is an open doodle/drawing challenge rather than a technical one. 
So, draw something up on a piece of paper and share it in the comments below.
Thus, you don't necessarily have to fork the repo and open a PR in order to participate. 

**Prize**: If the winner is studying at KGP, they get a GitHub Octocat sticker and a dinner treat!

**Voting:** Use 👍 if you like a doodle. (Please do not use 👎 as this be discouraging.)

**Deadline:** _Thursday, 25th October_

**Comment by kshitij10496** [comment]
Inspired by [Mr.Doodle](https://mrdoodle.com/)

![doodle101](https://lh3.googleusercontent.com/CljF_3ADSzf7KOLtaWaL2aWu-wT6N2d9kdSlqGSipreZsy6FitFGn3rkgRnUTrKSE9PraCjJiR-N-cQbgwnK-PWiejLJrinTyAFV7aKq6BOuMzwmOK4b-Qhf-vk90eHJ_zdZU63kEvkuWzLv5QcW3J_5eV1F6OSNphYylJm-lxwEwDsjuOMrjE6vzQN6UO2JU0BEIjrAMtlkIgMwhpqQcoLwIzFoA1Q5aG4K-xcPhGI-lJlHuHm4b_ef2N6mOjdQ2ZyG_PyXAWwN8gHiXc8TC4roNGR7xQiW6aX85IqsZGg1T7lP5bcp9YwT3TCwih7okOMX8zD6BmSZfx1mwclRsa1GBgI1hcuvBnF1Kg4iPP1m-S4lzecyUdW0fRMINxQE_aPgQvncAplECEf-tfO8hLC9L1yuhAX2MI0bbFkBFaIqCs9FYXMMvptjqS2SuqbUCm2cd7Ph875uCBgQV3EB1ZFW6vQrttDL7NNvdYPw0L9-KjakZG_dcE_Tv6oDiUgg-9sl87ImkvXPA2_kQxNwKc-7lv33EpPDRebNueE5OAvXDlQUdjal5yJJkFBUXyY492wCREHhvsRa2I_JBPfEHdAudliPPcKeZCD7ODmdPF_5XwQ74Ud1p0rAlCfEY94=w738-h984-no)

**Comment by themousepotato** [comment]
cc @xypnox

**Comment by nupurgunwant** [comment]
![img_20181018_171944__01__01](https://user-images.githubusercontent.com/19436036/47152409-440a9000-d2fa-11e8-8351-8fdf1151b0f3.jpg)

Fact :  A neamus lion was strangled by Hercules. Thus, his skin was worn by Hercules as a symbol of strength

**Comment by kshitij10496** [comment]
Some reference to Hercules' 12 labours would be super cool. 😃

**Comment by HunGARE** [comment]
Eleventh Labour: Golden Apples of the Hesperides
![hungare_hercules](https://user-images.githubusercontent.com/19934910/47231692-964fbd80-d39b-11e8-850b-fbc4eadaa7b2.jpg)

**Comment by HunGARE** [comment]
Eleventh Labour: Golden Apples of the Hesperides

![hungare_hercules](https://user-images.githubusercontent.com/19934910/47231727-bd0df400-d39b-11e8-80af-ab8d14ca8a3c.jpg)

**Comment by xypnox** [comment]
Too late but here is my rendition of strength/power. A cap with a bunch of paper underneath it 

![](https://i.imgur.com/0PvgneZ.jpg)

**Comment by kshitij10496** [comment]
Oh, yes! I almost forgot.
Based on the current vote count, we will add @nupurgunwant's artwork as the logo. 😄 
Thanks a lot!
