### ISSUE TITLE
Hercules application error on heroku, app not working

### ISSUE THREAD

**Issue by Ayushk4** [kshitij10496/hercules#42]
https://hercules-10496.herokuapp.com/api/v1/department/info/all
Tried, various links, none works.

**Comment by kshitij10496** [comment]
I don't know why but the app crashed possibly due to some Heroku issue.
It should be working after a quick dyno restart. 😅

**Comment by Ayushk4** [comment]
It crashed again :smile: . It seems that the 404 handler is not working.

I request for a course code that did not exist (accidentaly) : https://hercules-10496.herokuapp.com/api/v1/course/timetable/MA6102

**Comment by kshitij10496** [comment]
Got the bug!

I have used `log.Fatal` for debugging invalid requests. 🙈 
This is causing the app to crash when the user is making invalid requests.
All the logs should be `log.Print` for now. 

Making a quick fix to master.

**Comment by Ayushk4** [comment]
I will keep finding bugs to bother you :stuck_out_tongue: .

**Comment by Ayushk4** [comment]
It shows internal server err : 500 instead of bad request or 404.

**Comment by kshitij10496** [comment]
> I will keep finding bugs to bother you 😛 .

That's actually great! 
I think those would be good places to get started with contributing to the API server.
