### ISSUE TITLE
Make sure that a faculty can't be taking multiple subjects in same time on validation

### ISSUE THREAD

**Issue by themousepotato** [kshitij10496/hercules#46]
Check this instance:
```
        {
            "course": {
                "name": "GRAPH THEORY AND ALGORITHMS",
                "code": "MA60041",
                "credits": 4
            },
            "slot": {
                "time": {
                    "day": "Monday",
                    "time": "12 PM"
                },
                "slot": "D4"
            },
            "rooms": [
                "NR223"
            ]
        },
        {
            "course": {
                "name": "GRAPH THEORY AND ALGORITHMS",
                "code": "MA61003",
                "credits": 4
            },
            "slot": {
                "time": {
                    "day": "Monday",
                    "time": "12 PM"
                },
                "slot": "D4"
            },
            "rooms": [
                "NR223"
            ]
        }
    ],
```

Here, `MA60041` and `MA61003` appears to be different but, under the same name `GRAPH THEORY AND ALGORITHMS`, same time `12 PM`. Write validation conditions for such cases. @kshitij10496 WDYT?

**Comment by kshitij10496** [comment]
This is actually not a bug. What this duplication means is that a particular course has multiple course codes.

**Comment by themousepotato** [comment]
A validation should be there, no? Say `wimp` uses `hercules` for the data. It confuses the app as a faculty can't take multiple subjects at the same time. How can I particular course have multiple course codes. One of them should be outdated, no?

**Comment by kshitij10496** [comment]
> How can I particular course have multiple course codes.

Basically, different course codes refer to the academic batch registered for the course.
For example, my batch uses the course code "MA51121" for this particular course while the 2 years M.Sc use a different one. Essentially, the mapping between a course and course codes is one-to-many. In order to port this to `wimp`, we can simply iterate over the list of course and fetch only the rooms and do not bother with the course details.
